using Harmony;

namespace Chroma
{
    /// <summary>
    /// Attach this interface to any plugin used to extend Chroma.
    /// </summary>
    public interface IChromaExtension
    {
        /// <summary>
        /// Called after Chroma starts, use this to register events - especially those that need to happen on first load.
        /// </summary>
        /// <param name="chromaPlugin">The core Chroma plugin</param>
        void ChromaApplicationStarted(ChromaPlugin chromaPlugin);

        /// <summary>
        /// Called after Chroma registers a HarmonyInstance, but before any other action is taken.
        /// Chroma extensions should register their Harmony patches here.
        /// </summary>
        /// <returns>The harmony instance generated by the extension.  Null if none.</returns>
        HarmonyInstance PatchHarmony();
    }
}