//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chroma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceTextFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTextFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chroma.ResourceTextFiles", typeof(ResourceTextFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=6&gt;&lt;align=&quot;center&quot;&gt;&lt;mspace=4&gt;CHROMA&lt;/mspace&gt; %VER%&lt;/align&gt;&lt;/size&gt;
        ///
        ///Welcome, %USERNAME%!  
        ///
        ///Here at the luxurious suite of Chroma we value your eye-cone-thingies.
        ///
        ///A recent trend of duochromitis has plagued the VR community since the release of a particularly popular music game I can&apos;t remember the name of right now, but the important thing is Chroma is here to slap some spectrum back in your drab two-tone lives.
        ///
        ///Embrace a cacophony of Technicolour lightwaves, or if you want to paint it all bla [rest of string was truncated]&quot;;.
        /// </summary>
        public static string chromaNotes {
            get {
                return ResourceManager.GetString("chromaNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=6&gt;&lt;mspace=4&gt;&lt;align=&quot;center&quot;&gt;CHROMA&lt;/align&gt;&lt;/mspace&gt;&lt;/size&gt;
        ///People who did stuff.  Yaaaaay!
        ///
        ///&lt;align=&quot;center&quot;&gt;&lt;b&gt;Lead Developer&lt;/b&gt;&lt;/align&gt;
        ///&lt;b&gt;&lt;color=#00aaaa&gt;SkyKiwiTV&lt;/color&gt;&lt;/b&gt;
        ///-&lt;indent=3&gt;Made the thing&lt;/indent&gt;
        ///-&lt;indent=3&gt;Yeah yeah we already knew that big whoop&lt;/indent&gt;
        ///-&lt;indent=3&gt;Thinks squeaksies is the best&lt;/indent&gt;
        ///
        ///
        ///&lt;align=&quot;center&quot;&gt;&lt;b&gt;Significant Contributors&lt;/b&gt;&lt;/align&gt;
        ///&lt;b&gt;&lt;color=#9b59b6&gt;Arti&lt;/color&gt;&lt;/b&gt; - Enabler
        ///-&lt;indent=3&gt;Learned me good in the ways of Harmony&lt;/indent&gt;
        ///-&lt;inden [rest of string was truncated]&quot;;.
        /// </summary>
        public static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;size=6&gt;&lt;mspace=4&gt;&lt;align=&quot;center&quot;&gt;SAFETY WAIVER&lt;/align&gt;&lt;/mspace&gt;&lt;/size&gt;
        ///
        ///Certain features of Chroma and its extension mods require you to agree to a safety warning.  Both the reasoning behind this, and the instructions to do so, are below.
        ///
        ///If you are planning to enable these features, it is imperative to know you are doing so
        ///&lt;align=&quot;center&quot;&gt;&lt;color=&quot;red&quot;&gt;AT YOUR OWN RISK&lt;/color&gt;&lt;/align&gt;
        ///
        ///Below are the features explicitly blocked unless the safety waiver has been signed.  Not all of these features ar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string safetyWaiver {
            get {
                return ResourceManager.GetString("safetyWaiver", resourceCulture);
            }
        }
    }
}
