name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - Heck/**
    - Chroma/**
    - NoodleExtensions/**
    - Heck.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        project-path: [ Heck/Heck.csproj, NoodleExtensions/NoodleExtensions.csproj, Chroma/Chroma.csproj ]
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.39.0 ]
    uses: Aeroluna/beat-saber-workflows/.github/workflows/build-version-release.yml@master
    with:
      project-path: ${{ matrix.project-path }}
      game-version: ${{ matrix.game-version }}
      additional-project-paths: '["Heck/Heck.csproj"]'
      additional-sources: '{"CustomJSONData": "Aeroluna/CustomJSONData"}'
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/beat-saber-workflows/.github/workflows/create-release-from-date.yml@master
    secrets: inherit