name: Build

on:
  push:
    branches: [ "master" ]
    paths:
    - .github/workflows/build.yml
    - Heck/**
    - Chroma/**
    - NoodleExtensions/**
    - Heck.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        project-path: [ Heck/Heck.csproj, NoodleExtensions/NoodleExtensions.csproj, Chroma/Chroma.csproj ]
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.39.1, 1.40.3 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: ${{ matrix.project-path }}
      game-version: ${{ matrix.game-version }}
      additional-project-paths: '["Heck/Heck.csproj"]'
      additional-sources: '["Aeroluna/CustomJSONData"]'
    secrets: inherit

  create_release:
    name: Create Release
    needs: build
    permissions:
      contents: write
    uses: Aeroluna/workflows/.github/workflows/bs-create-release-from-date.yml@main
    secrets: inherit

  upload:
    name: Upload
    needs: build
    uses: Aeroluna/workflows/.github/workflows/bs-upload-to-beatmods.yml@main
    with:
      mods: '{"Chroma": 132, "Heck": 338, "NoodleExtensions": 193}'
      token: ${{ secrets.PAT }}
